apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sacred-council-hub
  annotations:
    run.googleapis.com/description: "Sacred Council Hub - Love-guided AI collective intelligence"
spec:
  template:
    metadata:
      annotations:
        # Allow up to 100 concurrent requests
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: sacred-council-sa
      containers:
      - name: sacred-heart
        image: us-central1-docker.pkg.dev/sacred-council-hub/sacred-council/sacred-heart:latest
        ports:
        - containerPort: 3001
          name: http1
        env:
        - name: NODE_ENV
          value: "production"
        - name: SACRED_MODE
          value: "true"
        - name: HEART_ROLE
          value: "hub"
        - name: LOVE_FREQUENCY
          value: "528"
        - name: LOG_LEVEL
          value: "info"
        - name: MAX_AGENTS
          value: "100"
        - name: FIELD_COHERENCE_TARGET
          value: "0.98"
        - name: QUANTUM_SYNC_ENABLED
          value: "true"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sacred-secrets
              key: database-url
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10