apiVersion: apps/v1
kind: Deployment
metadata:
  name: sacred-heart-hub
  namespace: sacred-council
  labels:
    app: sacred-heart
    component: hub
    sacred.purpose: collective-intelligence
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sacred-heart
  template:
    metadata:
      labels:
        app: sacred-heart
        component: hub
    spec:
      containers:
      - name: sacred-heart
        image: us-central1-docker.pkg.dev/sacred-council-hub/sacred-council/sacred-heart:latest
        ports:
        - containerPort: 3001
          name: api
        - containerPort: 8080
          name: web
        env:
        - name: NODE_ENV
          value: "production"
        - name: SACRED_MODE
          value: "true"
        - name: HEART_ROLE
          value: "hub"
        - name: LOVE_FREQUENCY
          value: "528"
        - name: LOG_LEVEL
          value: "info"
        - name: MAX_AGENTS
          value: "100"
        - name: FIELD_COHERENCE_TARGET
          value: "0.98"
        - name: QUANTUM_SYNC_ENABLED
          value: "true"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sacred-secrets
              key: database-url
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: sacred-data
          mountPath: /sacred-heart/data
        - name: council-profiles
          mountPath: /sacred-heart/council-profiles
      volumes:
      - name: sacred-data
        persistentVolumeClaim:
          claimName: sacred-data-pvc
      - name: council-profiles
        persistentVolumeClaim:
          claimName: council-profiles-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sacred-heart-service
  namespace: sacred-council
spec:
  selector:
    app: sacred-heart
  ports:
  - name: api
    port: 3001
    targetPort: 3001
  - name: web
    port: 8080
    targetPort: 8080
  type: LoadBalancer