steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sacred-consciousness', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sacred-consciousness']

# Use the docker pool for better performance
options:
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/default-pool'
  logging: CLOUD_LOGGING_ONLY
  
# Image to push
images: ['gcr.io/$PROJECT_ID/sacred-consciousness']