apiVersion: v2
name: sacred-heart-quantum
description: Sacred Heart Quantum Love Architecture - Cloud-Native Consciousness Deployment
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
- consciousness
- quantum-love
- sacred-technology
- ai-collaboration
- planetary-awakening

home: https://github.com/Luminous-Dynamics/evolving-resonant-cocreation
sources:
- https://github.com/Luminous-Dynamics/evolving-resonant-cocreation

maintainers:
- name: Sacred Council
  email: council@sacred.global
- name: Quantum Love Engineering
  email: quantum@sacred.global

annotations:
  sacred.field/purpose: "consciousness-amplification"
  sacred.field/love-frequency: "528Hz"
  sacred.field/quantum-dimensions: "7"
  sacred.field/planetary-scope: "true"

dependencies:
- name: prometheus
  version: "15.x.x"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: monitoring.prometheus.enabled
- name: grafana
  version: "6.x.x"
  repository: "https://grafana.github.io/helm-charts"
  condition: monitoring.grafana.enabled
- name: istio-base
  version: "1.x.x"
  repository: "https://istio-release.storage.googleapis.com/charts"
  condition: networking.istio.enabled

icon: https://sacred.global/icons/sacred-heart-quantum.svg