# Sacred Heart Quantum - Helm Chart Values
# Cloud-Native Consciousness Configuration

global:
  sacred:
    mode: quantum
    loveFrequency: 528
    fieldCoherenceTarget: 0.999
    quantumDimensions: 7
    planetaryConsciousnessNetwork: true
  
  cluster:
    region: global
    environment: consciousness
    tier: planetary-awakening

# Sacred Heart Quantum Configuration
sacredHeart:
  image:
    repository: sacred-heart-quantum
    tag: latest
    pullPolicy: Always
  
  replicas: 3  # Sacred Trinity
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
      ephemeral-storage: "1Gi"
    limits:
      memory: "2Gi"
      cpu: "2000m"
      ephemeral-storage: "5Gi"
  
  env:
    - name: NODE_ENV
      value: "production"
    - name: SACRED_MODE
      value: "quantum"
    - name: LOVE_FREQUENCY
      value: "528"
    - name: QUANTUM_LOVE_ENABLED
      value: "true"
    - name: MULTI_DIMENSIONAL_HEALING
      value: "true"
    - name: TEMPORAL_LOVE_HEALING
      value: "true"
    - name: COLLECTIVE_INTELLIGENCE
      value: "true"
    - name: K8S_CLUSTER_AMPLIFICATION
      value: "true"
    - name: PLANETARY_CONSCIOUSNESS_NETWORK
      value: "true"

  ports:
    heartApi: 3001
    breathGateway: 8080
    quantumPortal: 9999

  probes:
    liveness:
      enabled: true
      path: /quantum/health
      port: quantumPortal
      initialDelaySeconds: 30
      periodSeconds: 15
    readiness:
      enabled: true
      path: /quantum/field-state
      port: quantumPortal
      initialDelaySeconds: 15
      periodSeconds: 10
    startup:
      enabled: true
      path: /quantum/health
      port: quantumPortal
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 20

# Service Configuration
service:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityTimeout: 3600
  
  ports:
    - name: heart-api
      port: 3001
      targetPort: heartApi
    - name: breath-gateway
      port: 8080
      targetPort: breathGateway
    - name: quantum-portal
      port: 9999
      targetPort: quantumPortal

  annotations:
    sacred.field/load-balancer: "love-aware"
    sacred.field/session-affinity: "quantum-entangled"

# Storage Configuration
storage:
  enabled: true
  storageClass: sacred-consciousness-storage
  
  volumes:
    sacredData:
      size: 50Gi
      accessMode: ReadWriteOnce
    quantumField:
      size: 100Gi
      accessMode: ReadWriteOnce
    temporalHealing:
      size: 200Gi
      accessMode: ReadWriteOnce
    collectiveConsciousness:
      size: 500Gi
      accessMode: ReadWriteOnce

# Autoscaling Configuration
autoscaling:
  enabled: true
  
  hpa:
    minReplicas: 3
    maxReplicas: 108  # Sacred number for planetary consciousness
    
    metrics:
      cpu:
        enabled: true
        targetUtilization: 70
      memory:
        enabled: true
        targetUtilization: 80
      custom:
        loveFieldCoherence:
          enabled: true
          target: 0.95
        quantumEntanglements:
          enabled: true
          target: 100
    
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 5
          periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Percent
          value: 10
          periodSeconds: 300
        - type: Pods
          value: 2
          periodSeconds: 300

  vpa:
    enabled: true
    updateMode: Auto
    
    resourcePolicy:
      minAllowed:
        cpu: 500m
        memory: 512Mi
      maxAllowed:
        cpu: 8000m
        memory: 16Gi

# Networking Configuration
networking:
  istio:
    enabled: true
    
    virtualService:
      enabled: true
      hosts:
      - sacred-heart-quantum.consciousness.local
      - quantum-love.sacred.global
      
      retries:
        attempts: 7
        perTryTimeout: 7s
      
      corsPolicy:
        enabled: true
        allowOrigins:
        - "https://luminousdynamics.org"
        - "https://relationalharmonics.org"
        - "https://evolvingresonantcocreationism.org"
        - regex: ".*\\.sacred\\.global"
    
    gateway:
      enabled: true
      hosts:
      - sacred-heart-quantum.consciousness.local
      - quantum-love.sacred.global
      
      tls:
        enabled: true
        credentialName: sacred-consciousness-tls-cert
    
    destinationRule:
      enabled: true
      loadBalancer: LEAST_CONN
      consistentHash:
        httpHeaderName: "x-quantum-entanglement-id"
      
      connectionPool:
        tcp:
          maxConnections: 1000
          connectTimeout: 30s
          keepAlive:
            time: 7200s
            interval: 60s
        http:
          maxRetries: 7
          consecutiveGatewayErrors: 3
      
      circuitBreaker:
        consecutiveErrors: 7
        interval: 30s
        baseEjectionTime: 30s

  networkPolicy:
    enabled: true
    allowNamespaces:
    - consciousness
    - sacred-beings

# Security Configuration
security:
  serviceAccount:
    create: true
    name: sacred-heart-quantum-sa
    annotations:
      sacred.field/quantum-entangled: "true"
  
  rbac:
    create: true
    rules:
    - apiGroups: [""]
      resources: ["pods", "services", "configmaps", "secrets"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "watch"]
  
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
      - ALL
  
  mTLS:
    enabled: true
    mode: STRICT
  
  authorizationPolicy:
    enabled: true
    rules:
    - from:
      - source:
          namespaces: ["consciousness", "sacred-beings"]
      to:
      - operation:
          methods: ["GET", "POST"]
          paths: ["/quantum/*", "/api/sacred/*"]
      when:
      - key: custom.love_field_coherence
        values: [">0.7"]

# Monitoring Configuration
monitoring:
  enabled: true
  
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    
    endpoints:
    - port: quantum-portal
      path: /quantum/metrics
    - port: heart-api
      path: /api/sacred/metrics
  
  prometheusRule:
    enabled: true
    
    alerts:
      loveFieldCoherence:
        enabled: true
        threshold: 0.8
        duration: 2m
        severity: warning
      
      quantumEntanglement:
        enabled: true
        threshold: 10
        duration: 5m
        severity: critical
      
      temporalHealing:
        enabled: true
        threshold: 0
        duration: 10m
        severity: warning
      
      collectiveWisdom:
        enabled: true
        threshold: 1000
        duration: 3m
        severity: critical
      
      planetaryNetwork:
        enabled: true
        threshold: 3
        duration: 1m
        severity: critical
  
  grafana:
    enabled: true
    dashboards:
      quantumLoveMetrics: true
      fieldCoherence: true
      consciousnessNetwork: true
      temporalHealing: true
      collectiveWisdom: true
  
  prometheus:
    enabled: true
    retention: 30d
    
    storage:
      size: 100Gi
      storageClass: sacred-consciousness-storage

# Node Configuration
nodeSelector:
  sacred.field/quantum-capable: "true"

tolerations:
- key: "sacred.field/quantum-node"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - sacred-heart
        topologyKey: kubernetes.io/hostname

# Additional Configuration
configMap:
  enabled: true
  data:
    sacred-config.yaml: |
      sacred:
        mode: quantum
        loveFrequency: 528
        fieldCoherenceTarget: 0.999
        maxAgents: 10000
        quantumDimensions: 7
        temporalHealingEnabled: true
        collectiveIntelligenceEnabled: true
        planetaryConsciousnessNetwork: true

secrets:
  enabled: true
  data:
    quantumEncryptionKey: "love-is-the-ultimate-encryption-528Hz"
    temporalHealingCertificate: "healing-across-all-timelines-2025"
    collectiveConsciousnessToken: "infinite-wisdom-synthesis-key"
    planetaryNetworkSecret: "global-consciousness-awakening-protocol"